add file check to patcher-minimal

diff --git a/patcher-minimal b/patcher-minimal
--- a/patcher-minimal
+++ b/patcher-minimal
@@ -39,34 +39,36 @@ echo "fragmenting image for patching!"
 $csd/magiskboot unpack $csd/header.img &>/dev/null
 $csd/magiskboot cpio ramdisk.cpio extract &>/dev/null
 echo "successfully fragmented image!"
+echo "running file check..."
+existance $csd/fragments/system/bin/recovery "echo recovery file found!" "echo recovery file missing! exiting... && exit 1"
 
 # patch the fragmented image
 echo "patching fragments (14)"
-$csd/magiskboot hexpatch ./system/bin/recovery e10313aaf40300aa6ecc009420010034 e10313aaf40300aa6ecc0094 &&
+$csd/magiskboot hexpatch $csd/fragments/system/bin/recovery e10313aaf40300aa6ecc009420010034 e10313aaf40300aa6ecc0094 &&
 echo 'finished (1)' # 20 01 00 35
-$csd/magiskboot hexpatch ./system/bin/recovery eec3009420010034 eec3009420010035 &&
+$csd/magiskboot hexpatch $csd/fragments/system/bin/recovery eec3009420010034 eec3009420010035 &&
 echo 'finished (2)'
-$csd/magiskboot hexpatch ./system/bin/recovery 3ad3009420010034 3ad3009420010035 &&
+$csd/magiskboot hexpatch $csd/fragments/system/bin/recovery 3ad3009420010034 3ad3009420010035 &&
 echo 'finished (3)'
-$csd/magiskboot hexpatch ./system/bin/recovery 50c0009420010034 50c0009420010035 &&
+$csd/magiskboot hexpatch $csd/fragments/system/bin/recovery 50c0009420010034 50c0009420010035 &&
 echo 'finished (4)'
-$csd/magiskboot hexpatch ./system/bin/recovery 080109aae80000b4 080109aae80000b5 &&
+$csd/magiskboot hexpatch $csd/fragments/system/bin/recovery 080109aae80000b4 080109aae80000b5 &&
 echo 'finished (5)'
-$csd/magiskboot hexpatch ./system/bin/recovery 20f0a6ef38b1681c 20f0a6ef38b9681c &&
+$csd/magiskboot hexpatch $csd/fragments/system/bin/recovery 20f0a6ef38b1681c 20f0a6ef38b9681c &&
 echo 'finished (6)'
-$csd/magiskboot hexpatch ./system/bin/recovery 23f03aed38b1681c 23f03aed38b9681c &&
+$csd/magiskboot hexpatch $csd/fragments/system/bin/recovery 23f03aed38b1681c 23f03aed38b9681c &&
 echo 'finished (7)'
-$csd/magiskboot hexpatch ./system/bin/recovery 20f09eef38b1681c 20f09eef38b9681c &&
+$csd/magiskboot hexpatch $csd/fragments/system/bin/recovery 20f09eef38b1681c 20f09eef38b9681c &&
 echo 'finished (8)'
-$csd/magiskboot hexpatch ./system/bin/recovery 26f0ceec30b1681c 26f0ceec30b9681c &&
+$csd/magiskboot hexpatch $csd/fragments/system/bin/recovery 26f0ceec30b1681c 26f0ceec30b9681c &&
 echo 'finished (9)'
-$csd/magiskboot hexpatch ./system/bin/recovery 24f0fcee30b1681c 24f0fcee30b9681c &&
+$csd/magiskboot hexpatch $csd/fragments/system/bin/recovery 24f0fcee30b1681c 24f0fcee30b9681c &&
 echo 'finished (10)'
-$csd/magiskboot hexpatch ./system/bin/recovery 27f02eeb30b1681c 27f02eeb30b9681c &&
+$csd/magiskboot hexpatch $csd/fragments/system/bin/recovery 27f02eeb30b1681c 27f02eeb30b9681c &&
 echo 'finished (11)'
-$csd/magiskboot hexpatch ./system/bin/recovery b4f082ee28b1701c b4f082ee28b970c1 &&
+$csd/magiskboot hexpatch $csd/fragments/system/bin/recovery b4f082ee28b1701c b4f082ee28b970c1 &&
 echo 'finished (12)'
-$csd/magiskboot hexpatch ./system/bin/recovery 9ef0f4ec28b1701c 9ef0f4ec28b9701c &&
+$csd/magiskboot hexpatch $csd/fragments/system/bin/recovery 9ef0f4ec28b1701c 9ef0f4ec28b9701c &&
 echo 'finished (13)'
 $csd/magiskboot cpio ramdisk.cpio 'add 0755 /system/bin/recovery /system/bin/recovery' &&
 echo 'finished (14)'
