this is becoming more nightmarish by the second

diff --git a/patcher-minimal b/patcher-minimal
--- a/patcher-minimal
+++ b/patcher-minimal
@@ -27,6 +27,8 @@ echo "editing image..."
 off=$(grep -ab -o SEANDROIDENFORCE raw.img | tail -n 1 | cut -d : -f 1)
 dd if=raw.img of=header.img bs=4k count=$off iflag=count_bytes
 echo "made edit to image!"
+echo "running file check..."
+existance $csd/header.img "echo finished!" "echo file check on header.img failed && exit 1"
 
 # make key/signature
 echo "making keyfile..."
@@ -38,7 +40,9 @@ cd fragments
 echo "fragmenting image for patching!"
 $csd/magiskboot unpack $csd/header.img
 $csd/magiskboot cpio ramdisk.cpio extract
-existance $csd/fragments/system/bin/recovery "echo successfully fragmented image!" "echo fragmentation failed! exiting... && exit 1"
+echo "showing directory..."
+ls $csd/fragments
+existance $csd/fragments/system/bin/recovery "echo successfully fragmented image!" "echo fragmentation failed! && exit 1"
 
 # patch the fragmented image
 echo "patching fragments (14)"
